### ISSUE TITLE
invalid memory address or nil pointer dereference error returned when running test

### ISSUE THREAD

**Issue by miwiwa** [GoogleContainerTools/container-structure-test#142]
After installing the standalone binary through curl and pulling the example python image and yaml test file to my local Docker repo, I ran the command `./container-structure-test -test.v -image gcr.io/google-appengine/python python-structure-test.yaml`.

I'm getting `ERRO[0000] runtime error: invalid memory address or nil pointer dereference` returned.  I'm testing on RHEL7.2.

Any idea what I'm missing here?

**Comment by nkubala** [comment]
Hey @miwiwa, this is failing because you need to specify a subcommand to the main binary: `container-structure-test test <args...>`, `container-structure-test version`, etc. Also, your args are out of date with the latest binary: `-test.v` isn't a valid flag, you should use `-v [LEVEL]` instead, and you want `--image <image>` and `--config <config>`. 

I agree that this error is totally unhelpful though, tracking that here: https://github.com/GoogleContainerTools/container-structure-test/issues/135

**Comment by darrenhaken** [comment]
I came into this problem and the docs on the main site still encourage the use of `-test.v`. 

The docs this project really need some love :(
