### ISSUE TITLE
Support for negative case testing

### ISSUE THREAD

**Issue by dualbus** [GoogleContainerTools/container-structure-test#171]
Are there plans to support negative case / expectation testing?

i.e. I can write a test case like:

```
schemaVersion: '2.0.0'

metadataTest:
    exposedPorts: ['8080']
```

To indicate a positive expectation that port `8080` must be exposed. But what should I do to test that, say, port `22` is NOT exposed?

I'd expect something like (example):

```
schemaVersion: '2.0.0'

metadataTest:
    notExposedPorts: ['22']
```

To work

**Comment by nkubala** [comment]
@dualbus thanks for the issue. Hadn't really thought about this, but I can definitely see the use case. 

The only fields I think this would apply to in the `metadataTest` are ports, and possibly volumes (fields where there are multiples, so just writing a test to make sure it's either `nil` or `""` isn't enough). I suppose we could add `unexposedPorts` and `unmountedVolumes` to cover these cases. Would you be interested in sending a PR?

**Comment by KevinClaudius** [comment]
In order to protect against accidentally exposing an undeclared port or adding a volume without updating the test config yml, would it be possible to add a property like:

```
metadataTest:
  exposedPorts: [8080]
  noUndeclaredPorts: true
```
If `true`, `noUndeclaredPorts` would fail the `exposedPorts` metadata test if there are any ports exposed other than `8080`.  To maintain backwards compatibility, `noUndeclaredPorts` can default to `false`.

Similar property for volumes:

```
metadataTest:
  volumes:
    - "/tmp"
    - "/home/user"
  noUndeclaredVolumes: true
```
Would fail if the metadata test for volumes if there are any volumes other than these two explicitly-declared volumes.

**Comment by dualbus** [comment]
Sorry, I forgot about this issue.

Thank you for adding support for unexposedPorts and unmountedVolumes, @charlyx !
