### ISSUE TITLE
Tar driver usage

### ISSUE THREAD

**Issue by miwiwa** [GoogleContainerTools/container-structure-test#173]
I'm trying to use the tool within the IBM Cloud delivery pipeline.  I'm unable to use the Docker driver because each stage in the pipeline is run in a container and they currently don't support running Docker commands in them. They have their own commands to interact with the Docker registry.  I'm trying to use the tar driver until that support is there since the Readme listed it as the option to use without Docker.  When I run the container test using the tar driver each test is failing on the error below.

It looks like it's trying to run a Docker command (docker save?) to export the image as a tar.  Is this true that we need to run a docker command initially or is there a way we provide the tarball as part of the container test command? 

command run:  /home/pipeline/bin/container-structure-test test --driver tar --image <image name>:<tag> --config /home/pipeline/f334be90-4f92-45e4-bf19-346348240521/scripts/debian_test.yaml

Error: error creating driver: unable to retrieve auth token: invalid username/password
Retrieving image <image name>:<tag> from source Cloud Registry
Retrieving image <image name>:<tag> from source Local Daemon
=== RUN: apt-get
--- FAIL

**Comment by nkubala** [comment]
Hey @miwiwa, thanks for the issue and sorry this is a bit confusing.

The tar driver works by using our [go-containerregistry](https://github.com/google/go-containerregistry) library to retrieve an image's filesystem from any remote registry, or by consuming a local tarball on your machine, and extracting its contents on disk. It can then do any file-related operations, meaning it can run `fileExistenceTests` and `fileContentTests`, as well as the `metadataTest`. It *can't*, however, process any `commandTests`, because that would require running a container.

To provide your image to the tool, you can either specify a remote image, e.g.
`container-structure-test test --driver tar --image gcr.io/my_registry/my_image:latest --config cfg.yaml`

or, you can provide it a local tarball created from exporting an image (e.g. using `docker save`, more unlikely because the whole point is to not use docker).

Hope this helps! I'll clarify the example in the repo since it's pretty outdated.

**Comment by miwiwa** [comment]
Thanks for the reply.  I assume it's using a `crane pull` command to retrieve the image?  Looking through the issues in the go-containerregistry git project I found one related to 'crane auth issues' that stated, 

> crane by default uses the authentication set up in your ~/.docker/config.json

I'm thinking this is the issue I'm having without Docker installed, unless there's a secondary way to provide the auth?

Second question:  What's the command to include a tarball from local?  Would we reference the location in the `--image` flag?

**Comment by nkubala** [comment]
Hmm, yeah we're not plumbing any special auth through to the containerregistry calls so that could maybe be an issue. We're not using crane directly, but actually using the internals of the library to directly retrieve the image, it's mostly the same though. How are you authenticated to your registry? Have you tried manually writing some credentials to ~/.docker/config.json (just as a test) and seeing if that fixes the issue?

And that's right, to pass your tarball from a local filesystem, just provide it using the `--image` flag.

**Comment by nkubala** [comment]
@miwiwa going to close this issue for now. If you're still seeing auth issues, please open up another issue to track that.
