### ISSUE TITLE
Feature request: JUnit results

### ISSUE THREAD

**Issue by adriantorrie** [GoogleContainerTools/container-structure-test#207]
Add `junit` as an output format to allow CI tools, that can parse Junit results, to publish and report on test statistics as part of overall unit test results for a CI pipeline.

**Comment by nthienan** [comment]
Any plan on this?

**Comment by charlyx** [comment]
Hi 👋 

@gmembre-zenika and I are willing to work on it.

First we believe it'd be better to refactor the output feature.
As for now this feature relies on some `if` statements for the JSON output only.
We're planning to create a new interface called `Output` to handle several output format such as text or json: all this work will take place in a PR of its own.

Then, we will submit a new PR with a new implementation in order to handle JUnit format.
We might use [jstemmer/go-junit-report](https://github.com/jstemmer/go-junit-report)'s formatter for the JUnit output.

What do you think?

**Comment by nthienan** [comment]
@charlyx I'm not familiar with ` jstemmer/go-junit-report` as well as Golang, but I believe your idea is great. Go ahead! I'm looking forward to seeing this is implemented

**Comment by nilement** [comment]
Hi

@charlyx  and @gmembre-zenika  , are you still working on this? I would consider looking into and implemeting your proposed solution, or something similar, if you're not.

**Comment by charlyx** [comment]
@nilement our solution has not been confirmed by a maintainer yet. We're still willing to make it but won't waste time implementing it if it's not OK.

@donmccasland what do you think?

**Comment by nkubala** [comment]
hey @charlyx and everyone else, sorry for the radio silence on this. based on the community support here, I think we'd be happy to accept this as a feature of the tool. contributions are certainly welcome, I'll do my best to review the PR if and when it's sent :)

**Comment by nthienan** [comment]
@charlyx Are you still working on this? If yes, any update?

**Comment by charlyx** [comment]
Yes, @gmembre-zenika and I will be working on this issue soon.
