### ISSUE TITLE
Allow templating in test config files

### ISSUE THREAD

**Issue by bgauduch** [GoogleContainerTools/container-structure-test#265]
First of all, thanks a lot for your work and this very nice tool !

Allowing templating to generate multiple test config files (mostly command ones) would be a very nice addition.
Of course it is possible using some third party templating tools to do that, but including such feature directly in container-structure-test (and leveraging go templating) could be a good idea, WDYT ?

Exemple use case:
* When using Dockerfile Arguments to publish multiple version of the same tools using the same Dockerfile and image tags (for instance: https://github.com/Zenika/terraform-aws-cli/blob/master/Dockerfile#L2)
* And when using Github Actions job matrix (or any other tool / workflow) to release multiple image tags (for instance: https://github.com/Zenika/terraform-aws-cli/blob/master/.github/workflows/release.yml#L25)
* => Being able to use a template and iterate over all supported tool version for command test would be awesome !

[EDIT] Maybe I'm not savvy enough using container-structure-test and it is already possible to do such iteration using environment vars ? I just stumbled upon this: https://github.com/GoogleContainerTools/container-structure-test/pull/130

**Comment by nkubala** [comment]
@bgauduch thanks for the feature request. this is a bit tough because right now, the tool interprets any environment variables specified with `$` to be coming from the container it's testing against, not the host. so i'm not sure what the right way to tell the tool which variables should be interpreted from the host that's running the tests, versus the container the tests are being run against.

i'm definitely open to suggestions, but my gut instinct is that you're better off substituting variables from your pipelines into the test configs using a separate tool, and then feeding those to container-structure-test 🤷

**Comment by bgauduch** [comment]
Hello @nkubala, thanks for your feedback !
It confirm what I was thinking : generating config files from a template with placeholders substitution.

Thanks anyway, keep up the work on this very nice project 👍
